'use client';

import { useCallback, useEffect, useState } from 'react';
import { z } from 'zod';
import { RELEASE_READINESS_POLICY, ReadinessRunSchema, ReleaseWorkspaceSchema, type ReleaseWorkspace } from '@/lib/verification';

type Actor = 'author'|'qa';
const ErrorSchema = z.object({ error:z.string() });
const actorName = (actor:Actor) => actor === 'author' ? 'Alex Morgan · Author' as const : 'Jamie Chen · QA reviewer' as const;
async function api<T>(url:string,schema:z.ZodType<T>,init?:RequestInit):Promise<T> { const response = await fetch(url,{ ...init,headers:{ 'content-type':'application/json',...(init?.headers ?? {}) } });const body:unknown = await response.json();if (!response.ok) { const parsed=ErrorSchema.safeParse(body);throw new Error(parsed.success?parsed.data.error:`Request failed with status ${response.status}`); }return schema.parse(body); }

export function ReleaseWorkspacePanel({ actor,baseline,onWorkspaceRefresh,onNavigate }:{ actor:Actor;baseline:{ id:string;label:string }|null;onWorkspaceRefresh:()=>Promise<void>;onNavigate:(view:'verification'|'evidence')=>void }) {
  const [workspace,setWorkspace] = useState<ReleaseWorkspace|null>(null); const [busy,setBusy] = useState(false); const [error,setError] = useState<string|null>(null);
  const [label,setLabel] = useState(baseline ? `${baseline.label} verification release` : ''); const [codeRevision,setCodeRevision] = useState(baseline ? `fictional-${baseline.label.toLowerCase()}` : '');
  const load = useCallback(async () => setWorkspace(await api('/api/releases',ReleaseWorkspaceSchema)),[]);
  useEffect(() => { const timer=window.setTimeout(() => { void load().catch((reason:unknown) => setError(reason instanceof Error ? reason.message : 'Could not load releases.')); },0);return () => window.clearTimeout(timer); },[load]);
  const act = async (work:()=>Promise<void>) => { setBusy(true);setError(null);try { await work();await load();await onWorkspaceRefresh(); } catch (reason:unknown) { setError(reason instanceof Error ? reason.message : 'The release action failed.'); } finally { setBusy(false); } };
  const release = workspace?.releases.find((item) => item.baselineId === baseline?.id) ?? null;
  const latestReadiness = workspace?.latestReadiness ?? null;
  const run = latestReadiness?.releaseId === release?.id ? latestReadiness : null;
  const create = () => baseline && void act(async () => { await api('/api/releases',ReleaseWorkspaceSchema,{ method:'POST',body:JSON.stringify({ actor:actorName(actor),baselineId:baseline.id,label,codeRevision }) }); });
  const evaluate = () => release && void act(async () => { await api(`/api/releases/${release.id}/readiness`,ReadinessRunSchema,{ method:'POST',body:JSON.stringify({ actor:actorName(actor) }) }); });
  const ready = () => release && run && void act(async () => { await api(`/api/releases/${release.id}/verification-ready`,ReleaseWorkspaceSchema,{ method:'POST',body:JSON.stringify({ actor:actorName(actor),readinessRunId:run.id,confirmation:true }) }); });
  return <section className="view-content release-workspace"><div className="page-heading compact"><div><p className="eyebrow teal">Controlled outputs</p><h1>Releases</h1><p className="lede">Create an explicit planned release for an approved baseline, evaluate its fictional verification records, and let QA record the readiness transition.</p></div>{release && <span className={`status-badge ${release.status}`}>{release.status === 'verification_ready' ? 'Verification ready' : 'Planned'}</span>}</div>
    <div className="notice"><div className="notice-icon">i</div><p><b>Scope boundary.</b> Verification readiness is not residual-risk approval, CI certification, an electronic signature, or authorization to release a medical device.</p></div>{error && <div className="error-banner" role="alert">{error}</div>}
    {!release && <section className="workflow-stage"><div className="section-heading"><div><p className="eyebrow">Explicit release creation</p><h2>Create one planned release for {baseline?.label ?? 'an approved baseline'}</h2></div><span className="tag">fictional prototype record</span></div><div className="release-create-form"><label><span>Release label</span><input value={label} disabled={busy || actor !== 'author' || !baseline} onChange={(event) => setLabel(event.target.value)} /></label><label><span>Fictional code-revision reference</span><input value={codeRevision} disabled={busy || actor !== 'author' || !baseline} onChange={(event) => setCodeRevision(event.target.value)} /></label><button className="primary-button" disabled={busy || actor !== 'author' || !baseline || label.trim().length < 3 || codeRevision.trim().length < 2} onClick={create}>Create planned release</button></div>{actor !== 'author' && <small className="role-hint">Switch to Author to create the release record.</small>}</section>}
    {release && <><section className="workflow-stage"><div className="section-heading"><div><p className="eyebrow">Release record</p><h2>{release.label}</h2></div><code>{release.id}</code></div><dl className="release-facts"><div><dt>Baseline</dt><dd>{baseline?.label ?? release.baselineId}</dd></div><div><dt>Code revision</dt><dd>{release.codeRevision}</dd></div><div><dt>Created by</dt><dd>{release.createdBy}</dd></div><div><dt>Policy</dt><dd>{RELEASE_READINESS_POLICY.id}</dd></div></dl>{release.status === 'verification_ready' ? <div className="approval-complete"><span>✓</span><div><h3>Verification ready under release-readiness-v1</h3><p>Recorded by {release.verificationReadyBy} at {new Date(release.verificationReadyAt).toLocaleString()}. This is not “Released” or “Production ready.”</p></div></div> : <div className="release-actions"><button className="secondary-button" onClick={() => onNavigate('verification')}>Open Verification records</button><button className="primary-button" disabled={busy} onClick={evaluate}>Run versioned readiness policy</button></div>}</section>
      {run && <section className="workflow-stage"><div className="section-heading"><div><p className="eyebrow">{run.policyId} · version {run.policyVersion}</p><h2>{run.status === 'ready' ? 'Readiness checks passed' : 'Readiness blockers remain'}</h2></div><span className={`status-badge ${run.stale ? 'stale' : run.status}`}>{run.stale ? 'stale run' : run.status}</span></div><p>Input fingerprint <code>{run.inputFingerprint}</code></p><div className="readiness-results">{run.results.map((result) => <button key={result.id} className={result.status} onClick={() => onNavigate(result.code === 'RR-VER-001' ? 'verification' : 'evidence')}><span>{result.status}</span><div><b>{result.title}</b><p>{result.detail}</p></div><code>{result.subjectId}</code></button>)}</div>{release.status === 'planned' && <div className="approval-actions"><button className="secondary-button" disabled={busy} onClick={evaluate}>Refresh readiness evaluation</button><button className="approve-button" disabled={busy || actor !== 'qa' || run.status !== 'ready' || run.stale} onClick={ready}>Mark verification ready</button></div>}{release.status === 'planned' && actor !== 'qa' && <small className="role-hint">Switch to QA reviewer for the final verification-readiness transition.</small>}</section>}</>}
  </section>;
}
