'use client';

import { useEffect, useState } from 'react';
import { z } from 'zod';
import { SourceDetailSchema, SourceListResponseSchema, type Clarification, type SourceCandidate, type SourceCitation, type SourceDetail, type SourceListResponse } from '@/lib/source-domain';

type Actor = 'author'|'qa';
type SourceMode = 'inbox'|'review';
const ErrorSchema = z.object({ error:z.string(),runId:z.string().optional(),retryable:z.boolean().optional() });

class SourceRequestError extends Error {
  constructor(message:string,public readonly runId?:string,public readonly retryable?:boolean) { super(message); }
}

async function sourceApi<T>(url:string,schema:z.ZodType<T>,init?:RequestInit):Promise<T> {
  const response = await fetch(url,{ ...init,headers:{ 'content-type':'application/json',...(init?.headers ?? {}) } });
  const body:unknown = await response.json();
  if (!response.ok) { const parsed = ErrorSchema.safeParse(body); throw new SourceRequestError(parsed.success ? parsed.data.error : `Request failed with status ${response.status}`,parsed.success ? parsed.data.runId : undefined,parsed.success ? parsed.data.retryable : undefined); }
  return schema.parse(body);
}

function displayStatus(value:string):string { return value.replaceAll('_',' '); }
function actorName(actor:Actor):string { return actor === 'qa' ? 'Jamie Chen · QA reviewer' : 'Alex Morgan · Author'; }
function citationLabel(citation:SourceCitation):string { return citation.kind === 'source_span' ? citation.sourceRevisionId : `Clarification ${citation.clarificationId}`; }

function ClarificationCard({ item,actor,busy,onComplete }:{ item:Clarification;actor:Actor;busy:boolean;onComplete:(id:string,body:unknown)=>Promise<void> }) {
  const [answer,setAnswer] = useState(''); const [defer,setDefer] = useState(false);
  if (item.status !== 'open') return <article className="source-question resolved"><div className="source-card-top"><span className={`question-severity ${item.severity}`}>{item.severity}</span><span>{displayStatus(item.status)}</span></div><h3>{item.question}</h3><p>{item.answer ?? item.decisionReason}</p><small>{item.actor} · {new Date(item.updatedAt).toLocaleString()}</small></article>;
  return <article className="source-question"><div className="source-card-top"><span className={`question-severity ${item.severity}`}>{item.severity}</span><span>{displayStatus(item.kind)}</span></div><h3>{item.question}</h3><p>{item.rationale}</p><div className="citation-stack">{item.citations.map((citation) => <blockquote key={`${citation.sourceRevisionId}-${citation.quote}`}><b>{citation.sourceRevisionId}</b>{citation.quote}</blockquote>)}</div><label><span>{defer ? 'Reason for deferral' : 'Recorded answer'}</span><textarea value={answer} disabled={busy || actor !== 'author'} onChange={(event) => setAnswer(event.target.value)} placeholder={defer ? 'Explain why generation may proceed without this decision' : 'Record the product decision'} /></label><div className="source-actions"><button disabled={busy || actor !== 'author'} onClick={() => { setDefer(!defer);setAnswer(''); }}>{defer ? 'Answer instead' : 'Defer'}</button><button className="primary-button" disabled={busy || actor !== 'author' || answer.trim().length < 2} onClick={() => void onComplete(item.id,defer ? { action:'defer',reason:answer,actor:actorName(actor) } : { action:'answer',answer,actor:actorName(actor) })}>{defer ? 'Record deferral' : 'Save answer'}</button></div>{actor !== 'author' && <small className="source-role-note">Switch to Author to record source context.</small>}</article>;
}

function CandidateCard({ candidate,actor,busy,onDecision }:{ candidate:SourceCandidate;actor:Actor;busy:boolean;onDecision:(id:string,decision:'approved_for_baseline'|'rejected'|'revision_requested',reason:string)=>Promise<void> }) {
  const [reason,setReason] = useState('');
  return <article className={`source-candidate ${candidate.status}`}><div className="source-card-top"><div><span className="origin semantic">AI-derived</span>{candidate.type === 'requirement' && <span className="candidate-level">{candidate.level}</span>}</div><span className={`candidate-status ${candidate.status}`}>{displayStatus(candidate.status)}</span></div><p className="candidate-id">{candidate.id} · {candidate.policyVersion} · {candidate.model}</p><h3>{candidate.title}</h3><p className="candidate-statement">{candidate.statement}</p><p>{candidate.rationale}</p>{candidate.parentIds.length > 0 && <div className="candidate-parents"><span>Refines approved need</span>{candidate.parentIds.map((id) => <code key={id}>{id}</code>)}</div>}<div className="citation-stack">{candidate.citations.map((citation) => <blockquote key={`${citation.kind}-${citationLabel(citation)}-${citation.quote}`}><b>{citationLabel(citation)}</b>{citation.quote}</blockquote>)}</div>{candidate.advisoryClarificationIds.length > 0 && <div className="advisory-note">Carries {candidate.advisoryClarificationIds.length} unresolved advisory question{candidate.advisoryClarificationIds.length === 1 ? '' : 's'}.</div>}{candidate.status === 'pending_review' ? <><label><span>Review reason</span><input value={reason} disabled={busy || actor !== 'qa'} onChange={(event) => setReason(event.target.value)} placeholder="Record why this candidate is accepted or rejected" /></label><div className="source-actions"><button disabled={busy || actor !== 'qa' || reason.trim().length < 2} onClick={() => void onDecision(candidate.id,'rejected',reason)}>Reject</button><button disabled={busy || actor !== 'qa' || reason.trim().length < 2} onClick={() => void onDecision(candidate.id,'revision_requested',reason)}>Request revision</button><button className="approve-button" disabled={busy || actor !== 'qa' || reason.trim().length < 2} onClick={() => void onDecision(candidate.id,'approved_for_baseline',reason)}>Approve item</button></div>{actor !== 'qa' && <small className="source-role-note">Switch to QA reviewer to decide candidates.</small>}</> : <p className="reviewed-line">{candidate.reviewedBy} · {candidate.reviewedAt ? new Date(candidate.reviewedAt).toLocaleString() : ''}</p>}</article>;
}

function ImportPanel({ busy,onImport }:{ busy:boolean;onImport:(body:unknown)=>Promise<void> }) {
  const [title,setTitle] = useState(''); const [kind,setKind] = useState<'text'|'markdown'>('text'); const [content,setContent] = useState('');
  return <section className="import-panel"><div><p className="eyebrow">New source revision</p><h2>Import text or Markdown</h2><p>The prototype stores the exact imported content as an immutable source revision.</p></div><div className="import-fields"><label><span>Title</span><input value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Source title" /></label><label><span>Format</span><select value={kind} onChange={(event) => setKind(event.target.value === 'markdown' ? 'markdown' : 'text')}><option value="text">Plain text</option><option value="markdown">Markdown</option></select></label><label className="import-content"><span>Source content</span><textarea value={content} onChange={(event) => setContent(event.target.value)} placeholder="Paste meeting notes, an email thread, or a transcript" /></label><button className="primary-button" disabled={busy || title.trim().length < 3 || content.trim().length < 20} onClick={() => void onImport({ title,kind,content,actor:'Alex Morgan · Author' })}>Import immutable revision</button></div></section>;
}

function RevisionPanel({ busy,currentContent,onSave }:{ busy:boolean;currentContent:string;onSave:(content:string)=>Promise<void> }) {
  const [content,setContent] = useState(currentContent);
  return <section className="revision-panel"><div><p className="eyebrow">New immutable observation</p><h2>Import an updated source revision</h2><p>The approved evidence stays unchanged. BlueBridge records source drift and opens a fresh context-analysis path.</p></div><label><span>Updated text or Markdown</span><textarea value={content} onChange={(event) => setContent(event.target.value)} /></label><button className="primary-button" disabled={busy || content.trim().length < 20 || content === currentContent} onClick={() => void onSave(content)}>Create revision and impact work</button></section>;
}

export function SourceWorkspace({ mode,actor,workspace,onWorkspaceChange }:{ mode:SourceMode;actor:Actor;workspace:SourceListResponse;onWorkspaceChange:(workspace:SourceListResponse)=>void }) {
  const [selectedId,setSelectedId] = useState(workspace.sources[0]?.id ?? null); const [detail,setDetail] = useState<SourceDetail|null>(null); const [processingMode,setProcessingMode] = useState<'live'|'replay'>('live'); const [busy,setBusy] = useState(false); const [error,setError] = useState<string|null>(null); const [showImport,setShowImport] = useState(false); const [showRevision,setShowRevision] = useState(false);
  const selected = workspace.sources.find((source) => source.id === selectedId) ?? workspace.sources[0] ?? null;
  useEffect(() => { if (!selected) return; let current = true; void sourceApi(`/api/sources/${selected.id}`,SourceDetailSchema).then((value) => { if (current) { setDetail(value);setError(null); } }).catch((reason:unknown) => { if (current) setError(reason instanceof Error ? reason.message : 'Could not load the source.'); }); return () => { current = false; }; },[selected]);
  const refreshWorkspace = async () => { const next = await sourceApi('/api/sources',SourceListResponseSchema); onWorkspaceChange(next); };
  const refreshDetail = async () => { if (!selected) return;setDetail(await sourceApi(`/api/sources/${selected.id}`,SourceDetailSchema)); };
  const act = async (work:()=>Promise<SourceDetail>) => { setBusy(true);setError(null);try { const next = await work();setDetail(next);await refreshWorkspace(); } catch (reason:unknown) { setError(reason instanceof Error ? reason.message : 'The source action failed.');await Promise.allSettled([refreshDetail(),refreshWorkspace()]); } finally { setBusy(false); } };
  const importSource = async (body:unknown) => { await act(async () => { const next = await sourceApi('/api/sources',SourceDetailSchema,{ method:'POST',body:JSON.stringify(body) });setSelectedId(next.source.id);setShowImport(false);return next; }); };
  const reviseSource = async (content:string) => { if (!detail) return;await act(async () => { const next = await sourceApi(`/api/sources/${detail.source.id}`,SourceDetailSchema,{ method:'PUT',body:JSON.stringify({ content,actor:actorName(actor) }) });setShowRevision(false);return next; }); };
  const analyze = () => detail && act(() => sourceApi(`/api/sources/${detail.source.id}/analyse`,SourceDetailSchema,{ method:'POST',body:JSON.stringify({ mode:processingMode,actor:actorName(actor) }) }));
  const decideClarification = (id:string,body:unknown) => act(() => sourceApi(`/api/clarifications/${id}`,SourceDetailSchema,{ method:'POST',body:JSON.stringify(body) }));
  const generate = (kind:'user_needs'|'requirements') => detail && act(() => sourceApi(`/api/sources/${detail.source.id}/generate`,SourceDetailSchema,{ method:'POST',body:JSON.stringify({ kind,mode:processingMode,actor:actorName(actor) }) }));
  const decideCandidate = (id:string,decision:'approved_for_baseline'|'rejected'|'revision_requested',reason:string) => act(() => sourceApi(`/api/source-candidates/${id}/decision`,SourceDetailSchema,{ method:'POST',body:JSON.stringify({ decision,reason,actor:actorName(actor) }) }));
  const latestContextRun = detail?.runs.find((run) => run.kind === 'source_context') ?? null; const latestGenerationRun = detail?.runs.find((run) => run.kind === 'user_needs' || run.kind === 'requirements') ?? null; const userNeeds = detail?.candidates.filter((candidate) => candidate.type === 'user_need') ?? []; const requirements = detail?.candidates.filter((candidate) => candidate.type === 'requirement') ?? [];
  const canGenerateNeeds = detail?.source.status === 'ready_for_needs'; const canGenerateRequirements = detail?.source.status === 'ready_for_requirements';
  const visibleCandidates = mode === 'review' ? detail?.candidates ?? [] : [];
  const unresolved = detail?.clarifications.filter((item) => item.status === 'open') ?? [];
  return <section className="view-content source-workspace"><div className="page-heading compact"><div><p className="eyebrow teal">Inputs · controlled provenance</p><h1>{mode === 'review' ? 'Review centre' : 'Source inbox'}</h1><p className="lede">{mode === 'review' ? 'Decide AI-derived evidence one item at a time before it can enter a candidate baseline.' : 'Turn source revisions into cited, reviewable product evidence.'}</p></div>{mode === 'inbox' && <button className="primary-button" onClick={() => setShowImport(!showImport)}>{showImport ? 'Close import' : 'Import source'}</button>}</div>
    {showImport && <ImportPanel busy={busy} onImport={importSource} />}
    {error && <div className="error-banner" role="alert">{error}</div>}
    <div className="source-metrics"><article><span>Sources</span><strong>{workspace.sources.length}</strong><small>immutable revisions</small></article><article><span>Open review</span><strong>{workspace.reviewCount}</strong><small>questions and candidates</small></article><article><span>Approved items</span><strong>{workspace.approvedCandidateCount}</strong><small>awaiting baseline</small></article><article><span>Candidate baseline</span><strong>{workspace.candidateBaselineReady ? 'Ready' : 'Not ready'}</strong><small>coherence gate</small></article></div>
    <div className="source-layout"><aside className="source-list">{workspace.sources.map((source) => <button key={source.id} className={source.id === selected?.id ? 'selected' : ''} onClick={() => setSelectedId(source.id)}><span><code>{source.id}</code><em>{displayStatus(source.kind)}</em></span><b>{source.title}</b><small>Revision {source.revision} · {displayStatus(source.status)}</small>{source.requiredOpen > 0 && <i>{source.requiredOpen} required</i>}{source.candidateCount > 0 && <i className="candidate-count">{source.approvedCandidateCount}/{source.candidateCount} approved</i>}</button>)}</aside><div className="source-detail">{detail && detail.source.id === selected?.id ? <>
      <header className="source-detail-header"><div><span className="type-pill">{displayStatus(detail.source.kind)}</span><code>{detail.revision.id} · hash {detail.revision.contentHash}</code><h2>{detail.source.title}</h2></div><div className="source-header-actions"><span className={`candidate-status ${detail.source.status}`}>{displayStatus(detail.source.status)}</span>{mode === 'inbox' && <button disabled={actor !== 'author'} onClick={() => setShowRevision(!showRevision)}>{showRevision ? 'Cancel revision' : 'Add revision'}</button>}</div></header>
      <div className="source-flow"><span className={detail.runs.some((run) => run.kind === 'source_context') ? 'done' : 'active'}>1 Context</span><span className={userNeeds.length > 0 ? 'done' : canGenerateNeeds ? 'active' : ''}>2 User needs</span><span className={requirements.length > 0 ? 'done' : canGenerateRequirements ? 'active' : ''}>3 Requirements</span><span className={detail.source.status === 'candidate_baseline' || detail.source.status === 'baselined' ? 'done' : ''}>4 Baseline</span></div>
      {mode === 'inbox' ? <>{showRevision && <RevisionPanel key={detail.revision.id} busy={busy} currentContent={detail.revision.content} onSave={reviseSource} />}{detail.runs.some((run) => run.kind === 'source_revision_impact') && <div className="revision-impact"><b>Source drift recorded.</b> A new immutable revision exists; approved evidence was not changed. Run context analysis to create the next reviewed work.</div>}<section className="source-content"><div className="section-heading"><div><p className="eyebrow">Immutable source revision</p><h2>Original content</h2></div><span>{new Date(detail.revision.capturedAt).toLocaleString()}</span></div><pre>{detail.revision.content}</pre></section>
      <section className="source-processing"><div className="section-heading"><div><p className="eyebrow">Versioned analysis policy</p><h2>Context questions</h2></div><div className="processing-controls"><button className={processingMode === 'live' ? 'active' : ''} onClick={() => setProcessingMode('live')}>Live OpenRouter</button><button className={processingMode === 'replay' ? 'active' : ''} onClick={() => setProcessingMode('replay')}>Saved replay</button></div></div>{latestContextRun?.mode === 'replay' && latestContextRun.status === 'completed' && <div className="replay-notice"><b>Saved output</b> No fresh model result is being presented.</div>}{latestContextRun?.status === 'failed' && <div className="error-banner"><b>Live run failed.</b> {latestContextRun.error} Choose Retry live or select Saved replay explicitly.</div>}{!detail.runs.some((run) => run.kind === 'source_context' && run.status === 'completed') ? <div className="analysis-empty"><p>Run `source-context-v3` to find contradictions, ambiguities, missing decisions and scope questions.</p><button className="primary-button" disabled={busy || actor !== 'author'} onClick={() => void analyze()}>{busy ? 'Analysing…' : processingMode === 'live' && latestContextRun?.status === 'failed' ? 'Retry live analysis' : processingMode === 'live' ? 'Analyse with Luna via OpenRouter' : 'Load saved analysis'}</button>{actor !== 'author' && <small className="source-role-note">Switch to Author to process source context.</small>}</div> : <div className="question-list">{detail.clarifications.map((item) => <ClarificationCard key={item.id} item={item} actor={actor} busy={busy} onComplete={decideClarification} />)}</div>}</section>
      {latestGenerationRun?.status === 'failed' && <div className="error-banner"><b>Live generation failed.</b> {latestGenerationRun.error} Retry live generation or select Saved replay explicitly.</div>}
      <section className="generation-gate"><div><p className="eyebrow">Sequential generation</p><h2>{canGenerateNeeds ? 'Context gate passed' : canGenerateRequirements ? 'User-need review complete' : detail.source.status === 'needs_context' ? 'Required context remains' : detail.source.status === 'needs_review' ? 'Candidate review in progress' : 'Source processing'}</h2><p>{canGenerateNeeds ? 'Generate user needs from this revision and recorded answers.' : canGenerateRequirements ? 'Derive requirements only from the approved user needs.' : unresolved.some((item) => item.severity === 'required') ? 'Answer or defer each required question before generation.' : 'Open Review centre to decide the generated candidates.'}</p></div>{canGenerateNeeds && <button className="primary-button" disabled={busy || actor !== 'author'} onClick={() => void generate('user_needs')}>{processingMode === 'live' && latestGenerationRun?.kind === 'user_needs' && latestGenerationRun.status === 'failed' ? 'Retry live user needs' : 'Generate user needs'}</button>}{canGenerateRequirements && <button className="primary-button" disabled={busy || actor !== 'author'} onClick={() => void generate('requirements')}>{processingMode === 'live' && latestGenerationRun?.kind === 'requirements' && latestGenerationRun.status === 'failed' ? 'Retry live requirements' : 'Derive requirements'}</button>}</section></> : <section className="candidate-review"><div className="review-section-heading"><div><p className="eyebrow">{detail.source.title}</p><h2>{visibleCandidates.length} evidence candidates</h2></div><span>{visibleCandidates.filter((candidate) => candidate.status === 'pending_review').length} awaiting QA</span></div>{visibleCandidates.length === 0 ? <div className="analysis-empty"><p>Process this source and generate user needs before review work appears.</p></div> : <div className="candidate-list">{visibleCandidates.map((candidate) => <CandidateCard key={candidate.id} candidate={candidate} actor={actor} busy={busy} onDecision={decideCandidate} />)}</div>}{canGenerateRequirements && <div className="generation-gate"><div><p className="eyebrow">Next controlled step</p><h2>Derive requirements</h2><p>All user needs have been decided. Requirements will cite this source and refine approved need IDs.</p></div><button className="primary-button" disabled={busy || actor !== 'author'} onClick={() => void generate('requirements')}>Derive requirements</button></div>}</section>}
    </> : <div className="loading-state">Loading source…</div>}</div></div>
  </section>;
}

export function ConnectedSystemsPanel() {
  const systems = [
    { name:'GitHub',state:'Not connected',flow:'Repository and commit observations -> Components',detail:'Code proves what exists. A future sync will propose component drift and missing tests.' },
    { name:'Jira',state:'Not connected',flow:'Work records -> Change sets',detail:'Jira remains authoritative for tickets and assignment, not controlled evidence approval.' },
    { name:'CI verification',state:'Not connected',flow:'Executions -> Verification evidence',detail:'Future runs will attach results to test cases and releases without rewriting the test definition.' },
  ];
  return <section className="view-content"><div className="page-heading compact"><div><p className="eyebrow teal">Implementation inputs</p><h1>Connected systems</h1><p className="lede">Operational observations enter beside documents, but retain their own authority.</p></div><span className="conceptual-badge">Conceptual — not implemented</span></div><div className="connected-grid">{systems.map((system) => <article key={system.name}><div className="system-mark">{system.name.slice(0,2).toUpperCase()}</div><span>{system.state}</span><h2>{system.name}</h2><b>{system.flow}</b><p>{system.detail}</p><button disabled>Configure later</button></article>)}</div><section className="authority-strip"><div><span>Intent inputs</span><b>Documents · transcripts · email · Jira</b></div><strong>→</strong><div><span>Controlled product model</span><b>Needs · requirements · components · tests</b></div><strong>←</strong><div><span>Implementation inputs</span><b>Repositories · architecture · cloud · CI</b></div></section></section>;
}

export function BaselineWorkspace({ workspace,actor,onWorkspaceChange,currentBaseline='RR-1.0' }:{ workspace:SourceListResponse;actor:Actor;onWorkspaceChange:(workspace:SourceListResponse)=>void;currentBaseline?:string }) {
  const [busy,setBusy] = useState(false); const [error,setError] = useState<string|null>(null);
  const approve = async () => { setBusy(true);setError(null);try { const next = await sourceApi('/api/source-baselines/approve',SourceListResponseSchema,{ method:'POST',body:JSON.stringify({ actor:actorName(actor),confirmation:true }) });onWorkspaceChange(next); } catch (reason:unknown) { setError(reason instanceof Error ? reason.message : 'Could not approve the candidate baseline.'); } finally { setBusy(false); } };
  const decideImpact = async (id:string,decision:'accepted'|'rejected',reason:string) => { setBusy(true);setError(null);try { const next = await sourceApi(`/api/source-impact-suggestions/${id}/decision`,SourceListResponseSchema,{ method:'POST',body:JSON.stringify({ decision,reason,actor:actorName(actor) }) });onWorkspaceChange(next); } catch (cause:unknown) { setError(cause instanceof Error ? cause.message : 'Could not record the impact decision.'); } finally { setBusy(false); } };
  const runImpact = async (mode:'live'|'replay') => { if (!workspace.impactRun) return;setBusy(true);setError(null);try { const next = await sourceApi(`/api/sources/${workspace.impactRun.sourceId}/impact-analysis`,SourceListResponseSchema,{ method:'POST',body:JSON.stringify({ mode,actor:actorName(actor) }) });onWorkspaceChange(next); } catch (cause:unknown) { setError(cause instanceof Error ? cause.message : 'Could not run source impact analysis.');try { onWorkspaceChange(await sourceApi('/api/sources',SourceListResponseSchema)); } catch { /* Keep the actionable run error visible. */ } } finally { setBusy(false); } };
  const sourceReady = workspace.sources.filter((source) => source.status === 'candidate_baseline');
  return <section className="view-content"><div className="page-heading compact"><div><p className="eyebrow teal">Controlled outputs</p><h1>Baselines</h1><p className="lede">Review linked, semantic, and collection impacts before approving one coherent product state. Release records are created separately.</p></div><span className="baseline-pill"><span className="status-dot" />Current {currentBaseline}</span></div>{error && <div className="error-banner">{error}</div>}
    {workspace.impactRun?.status === 'failed' && <section className="source-impact-review"><div className="section-heading"><div><p className="eyebrow">Impact analysis failed</p><h2>No impact suggestions were created</h2></div><p>{workspace.impactRun.error}</p></div><div className="source-actions"><button disabled={busy || actor !== 'author'} onClick={() => void runImpact('replay')}>Load saved replay</button><button className="primary-button" disabled={busy || actor !== 'author'} onClick={() => void runImpact('live')}>Retry live impact analysis</button></div>{actor !== 'author' && <small>Switch to Author to start another processing run.</small>}</section>}
    {workspace.impactSuggestions.length > 0 && <section className="source-impact-review"><div className="section-heading"><div><p className="eyebrow">Automatic impact analysis · {workspace.impactRun?.policyVersion}</p><h2>Review proposed impact work</h2></div><p>{workspace.impactRun?.mode === 'replay' ? 'Saved replay selected' : 'Live OpenRouter'} · {workspace.impactRun?.model}. Suggestions never change controlled evidence automatically.</p></div><div className="source-impact-grid">{workspace.impactSuggestions.map((suggestion) => <SourceImpactCard key={suggestion.id} suggestion={suggestion} actor={actor} busy={busy} onDecision={decideImpact} />)}</div></section>}
    <div className="release-layout"><article className="candidate-baseline-card"><p className="eyebrow">Candidate baseline</p><h2>{sourceReady.length > 0 ? workspace.candidateBaselineReady ? 'Source-derived evidence is coherent' : 'Impact review required' : 'No candidate baseline ready'}</h2><div className="readiness-list"><span className={workspace.approvedCandidateCount > 0 ? 'pass' : ''}><b>{workspace.approvedCandidateCount}</b> item versions approved</span><span className={sourceReady.length > 0 ? 'pass' : ''}><b>{sourceReady.length}</b> source batches coherent</span><span className={workspace.impactSuggestions.length > 0 && workspace.impactSuggestions.every((item) => item.decision !== 'pending') ? 'pass' : ''}><b>{workspace.impactSuggestions.filter((item) => item.decision === 'pending').length}</b> impact decisions pending</span></div><button className="approve-button" disabled={busy || actor !== 'qa' || !workspace.candidateBaselineReady} onClick={() => void approve()}>{busy ? 'Approving…' : 'Approve immutable baseline'}</button>{actor !== 'qa' && <small>Switch to QA reviewer for the separate baseline decision.</small>}</article></div></section>;
}

function SourceImpactCard({ suggestion,actor,busy,onDecision }:{ suggestion:SourceListResponse['impactSuggestions'][number];actor:Actor;busy:boolean;onDecision:(id:string,decision:'accepted'|'rejected',reason:string)=>Promise<void> }) {
  const [reason,setReason] = useState('');
  return <article className={`source-impact-card ${suggestion.decision}`}><div className="source-card-top"><span className={`origin ${suggestion.origin}`}>{suggestion.origin === 'linked' ? 'Direct link' : suggestion.origin === 'collection' ? 'Collection context' : 'Semantic candidate'}</span><span className={`candidate-status ${suggestion.decision}`}>{displayStatus(suggestion.decision)}</span></div><div className="impact-target"><code>{suggestion.targetId}</code><b>{displayStatus(suggestion.proposedAction)}</b></div><p>{suggestion.rationale}</p><div className="impact-citations">{suggestion.citations.map((citation) => <code key={citation}>{citation}</code>)}</div>{suggestion.decision === 'pending' ? <><label><span>QA rationale</span><input value={reason} disabled={busy || actor !== 'qa'} onChange={(event) => setReason(event.target.value)} /></label><div className="source-actions"><button disabled={busy || actor !== 'qa' || reason.trim().length < 2} onClick={() => void onDecision(suggestion.id,'rejected',reason)}>Reject</button><button className="approve-button" disabled={busy || actor !== 'qa' || reason.trim().length < 2} onClick={() => void onDecision(suggestion.id,'accepted',reason)}>Accept impact work</button></div></> : <small>{suggestion.decidedBy}: {suggestion.decisionReason}</small>}</article>;
}

export function ConceptualPanel({ title,group='Product architecture',description,items }:{ title:string;group?:string;description:string;items:string[] }) {
  return <section className="view-content"><div className="page-heading compact"><div><p className="eyebrow teal">{group}</p><h1>{title}</h1><p className="lede">{description}</p></div><span className="conceptual-badge">Conceptual — not implemented</span></div><div className="conceptual-grid">{items.map((item,index) => <article key={item}><span>{String(index + 1).padStart(2,'0')}</span><h2>{item}</h2><p>This section is represented in the product architecture and will use the same provenance, review, version, and baseline controls.</p></article>)}</div></section>;
}
