import { z } from 'zod';
import { auditDetails } from './audit';
import {
  CreateDocumentPackageInputSchema,CreateDocumentRedlineInputSchema,CreateDocumentSnapshotInputSchema,CreateTemplateVersionInputSchema,
  DecideDocumentPackageInputSchema,DecideTemplateVersionInputSchema,DOCUMENT_PACKAGE_POLICY,DOCUMENT_REDLINE_VERSION,DOCUMENT_RENDERER_VERSION,
  DocumentFileSchema,DocumentPackageSchema,DocumentRedlineSchema,DocumentSnapshotSchema,DocumentTemplateVersionSchema,DocumentTemplateViewSchema,
  RetireTemplateInputSchema,SubmitTemplateVersionInputSchema,TemplateVersionIdSchema,UpdateTemplateVersionInputSchema,diffDocumentModels,nextTemplateVersionStatus,
  type DocumentSnapshot,type RenderedDocumentModel,
} from './document-domain';
import { buildZip,renderRedline,renderSnapshot } from './document-rendering';
import { canAcceptDocumentPackage } from './document-package-policy';
import { normalizeFilename,sha256Hex } from './final-release';
import { InvalidRequestError,WorkflowConflictError } from './http';
import { ensureWorkspace,listEvidenceForBaseline } from './repository';

const StringArraySchema=z.array(z.string());
const TypeArraySchema=z.array(z.enum(['intended_use','claim','user_need','requirement','hazard','risk_control','component','test','clinical_evidence','label']));
type TemplateVersion=z.infer<typeof DocumentTemplateVersionSchema>;

function now():string { return new Date().toISOString(); }
function makeId(prefix:string):string { return `${prefix}-${crypto.randomUUID().slice(0,8).toUpperCase()}`; }
function parseJson(value:string):unknown { return JSON.parse(value); }
function typeTitle(type:string):string { return type.replaceAll('_',' ').replace(/\b\w/g,(letter) => letter.toUpperCase()); }
function bytesBuffer(bytes:Uint8Array):ArrayBuffer { return Uint8Array.from(bytes).buffer; }
async function hashJson(value:unknown):Promise<string> { return sha256Hex(new TextEncoder().encode(JSON.stringify(value)).buffer); }

function auditStatement(db:D1Database,args:{ aggregateType:string;aggregateId:string;entityType:string;entityId:string;action:string;actor:string;createdAt:string;reason?:string;changes?:Array<{ field:string;oldValue:unknown;newValue:unknown }>;references?:Record<string,string> }) {
  return db.prepare('INSERT INTO audit_events (id,entity_type,entity_id,aggregate_type,aggregate_id,action,actor,details_json,schema_version,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)')
    .bind(makeId('AUD'),args.entityType,args.entityId,args.aggregateType,args.aggregateId,args.action,args.actor,JSON.stringify(auditDetails({ reason:args.reason,changes:args.changes,references:args.references })),1,args.createdAt);
}

type TemplateVersionRow={ id:string;templateId:string;version:number;title:string;description:string;typesJson:string;excludeFlagsJson:string;sectionOrderJson:string;requiredInPackage:number;status:string;createdBy:string;createdAt:string;submittedAt:string|null };
async function decisionsByVersion(db:D1Database) {
  const rows=await db.prepare('SELECT template_version_id AS templateVersionId,decision,reason,actor,created_at AS createdAt FROM document_template_decisions ORDER BY created_at DESC,id DESC').all<{ templateVersionId:string;decision:string;reason:string;actor:string;createdAt:string }>();const result=new Map<string,typeof rows.results[number]>();for (const row of rows.results) if (!result.has(row.templateVersionId)) result.set(row.templateVersionId,row);return result;
}
function templateVersionFromRow(row:TemplateVersionRow,decision:ReturnType<typeof decisionsByVersion> extends Promise<Map<string,infer T>> ? T|undefined : never):TemplateVersion {
  return DocumentTemplateVersionSchema.parse({ ...row,requiredInPackage:row.requiredInPackage===1,types:TypeArraySchema.parse(parseJson(row.typesJson)),excludeFlags:StringArraySchema.parse(parseJson(row.excludeFlagsJson)),sectionOrder:TypeArraySchema.parse(parseJson(row.sectionOrderJson)),decision:decision ? { decision:decision.decision,reason:decision.reason,actor:decision.actor,createdAt:decision.createdAt } : null });
}

export async function listTemplateWorkspace(db:D1Database) {
  await ensureWorkspace(db);const [templates,versions,decisions]=await Promise.all([
    db.prepare('SELECT id,code,current_version_id AS currentVersionId,status,retired_by AS retiredBy,retired_at AS retiredAt,retirement_reason AS retirementReason FROM document_templates ORDER BY code').all<{ id:string;code:string;currentVersionId:string;status:string;retiredBy:string|null;retiredAt:string|null;retirementReason:string|null }>(),
    db.prepare('SELECT id,template_id AS templateId,version,title,description,types_json AS typesJson,exclude_flags_json AS excludeFlagsJson,section_order_json AS sectionOrderJson,required_in_package AS requiredInPackage,status,created_by AS createdBy,created_at AS createdAt,submitted_at AS submittedAt FROM document_template_versions ORDER BY template_id,version DESC').all<TemplateVersionRow>(),decisionsByVersion(db),
  ]);const parsed=versions.results.map((row) => templateVersionFromRow(row,decisions.get(row.id)));return { templates:templates.results.map((template) => { const all=parsed.filter((version) => version.templateId===template.id);const current=all.find((version) => version.id===template.currentVersionId);if (!current) throw new Error(`Template ${template.id} has no current version.`);return DocumentTemplateViewSchema.parse({ ...template,currentVersion:current,versions:all }); }) };
}

export async function createTemplateVersion(db:D1Database,templateId:string,raw:unknown) {
  await ensureWorkspace(db);const input=CreateTemplateVersionInputSchema.parse(raw);const template=await db.prepare("SELECT id,status FROM document_templates WHERE id=?").bind(templateId).first<{ id:string;status:string }>();if (!template) return null;if (template.status!=='active') throw new WorkflowConflictError('Retired templates cannot receive new versions.');const open=await db.prepare("SELECT id FROM document_template_versions WHERE template_id=? AND status IN ('draft','qa_review')").bind(templateId).first<{ id:string }>();if (open) throw new WorkflowConflictError(`Template version ${open.id} is already open.`);const max=await db.prepare('SELECT MAX(version) AS version FROM document_template_versions WHERE template_id=?').bind(templateId).first<{ version:number|null }>();const version=(max?.version??0)+1;const id=TemplateVersionIdSchema.parse(`DTV-${templateId}-${version}`);const createdAt=now();await db.batch([
    db.prepare("INSERT INTO document_template_versions (id,template_id,version,title,description,types_json,exclude_flags_json,section_order_json,required_in_package,status,created_by,created_at,submitted_at) VALUES (?,?,?,?,?,?,?,?,?,'draft',?,?,NULL)").bind(id,templateId,version,input.title,input.description,JSON.stringify(input.types),JSON.stringify(input.excludeFlags),JSON.stringify(input.sectionOrder),input.requiredInPackage?1:0,input.actor,createdAt),
    auditStatement(db,{ aggregateType:'template',aggregateId:templateId,entityType:'document_template_version',entityId:id,action:'document_template_version_created',actor:input.actor,createdAt,changes:[{ field:'status',oldValue:null,newValue:'draft' }],references:{ templateId } }),
  ]);return listTemplateWorkspace(db);
}

export async function updateTemplateVersion(db:D1Database,id:string,raw:unknown) {
  await ensureWorkspace(db);const input=UpdateTemplateVersionInputSchema.parse(raw);const version=await db.prepare('SELECT template_id AS templateId,status FROM document_template_versions WHERE id=?').bind(id).first<{ templateId:string;status:string }>();if (!version) return null;if (version.status!=='draft') throw new WorkflowConflictError('Only draft template versions can be edited.');const changedAt=now();await db.batch([
    db.prepare('UPDATE document_template_versions SET title=?,description=?,types_json=?,exclude_flags_json=?,section_order_json=?,required_in_package=? WHERE id=?').bind(input.title,input.description,JSON.stringify(input.types),JSON.stringify(input.excludeFlags),JSON.stringify(input.sectionOrder),input.requiredInPackage?1:0,id),
    auditStatement(db,{ aggregateType:'template',aggregateId:version.templateId,entityType:'document_template_version',entityId:id,action:'document_template_version_edited',actor:input.actor,createdAt:changedAt,reason:input.reason,references:{ templateId:version.templateId } }),
  ]);return listTemplateWorkspace(db);
}

export async function submitTemplateVersion(db:D1Database,id:string,raw:unknown) {
  await ensureWorkspace(db);const input=SubmitTemplateVersionInputSchema.parse(raw);const row=await db.prepare('SELECT template_id AS templateId,status FROM document_template_versions WHERE id=?').bind(id).first<{ templateId:string;status:TemplateVersion['status'] }>();if (!row) return null;let next:'qa_review';try{next=nextTemplateVersionStatus(row.status,'submit');}catch{throw new WorkflowConflictError('Only a draft template version can be submitted.');}const submittedAt=now();await db.batch([
    db.prepare("UPDATE document_template_versions SET status=?,submitted_at=? WHERE id=? AND status='draft'").bind(next,submittedAt,id),
    auditStatement(db,{ aggregateType:'template',aggregateId:row.templateId,entityType:'document_template_version',entityId:id,action:'document_template_version_submitted',actor:input.actor,createdAt:submittedAt,changes:[{ field:'status',oldValue:'draft',newValue:'qa_review' }] }),
  ]);return listTemplateWorkspace(db);
}

export async function decideTemplateVersion(db:D1Database,id:string,raw:unknown) {
  await ensureWorkspace(db);const input=DecideTemplateVersionInputSchema.parse(raw);const row=await db.prepare('SELECT template_id AS templateId,status FROM document_template_versions WHERE id=?').bind(id).first<{ templateId:string;status:TemplateVersion['status'] }>();if (!row) return null;let status:'approved'|'rejected';try{status=input.decision==='accepted'?nextTemplateVersionStatus(row.status,'accept'):nextTemplateVersionStatus(row.status,'reject');}catch{throw new WorkflowConflictError('Only a template version in QA review can be decided.');}const prior=await db.prepare('SELECT id FROM document_template_decisions WHERE template_version_id=?').bind(id).first<{ id:string }>();if (prior) throw new WorkflowConflictError('This template version already has a QA decision.');const createdAt=now();const statements=[
    db.prepare('INSERT INTO document_template_decisions (id,template_version_id,decision,reason,actor,created_at) VALUES (?,?,?,?,?,?)').bind(makeId('DTD'),id,input.decision,input.reason,input.actor,createdAt),
    db.prepare('UPDATE document_template_versions SET status=? WHERE id=?').bind(status,id),
    auditStatement(db,{ aggregateType:'template',aggregateId:row.templateId,entityType:'document_template_version',entityId:id,action:`document_template_version_${input.decision}`,actor:input.actor,createdAt,reason:input.reason,changes:[{ field:'status',oldValue:'qa_review',newValue:status }] }),
  ];if (input.decision==='accepted') statements.push(db.prepare('UPDATE document_templates SET current_version_id=? WHERE id=?').bind(id,row.templateId));await db.batch(statements);return listTemplateWorkspace(db);
}

export async function retireTemplate(db:D1Database,id:string,raw:unknown) {
  await ensureWorkspace(db);const input=RetireTemplateInputSchema.parse(raw);const row=await db.prepare('SELECT status FROM document_templates WHERE id=?').bind(id).first<{ status:string }>();if (!row) return null;if (row.status!=='active') throw new WorkflowConflictError('The template is already retired.');const retiredAt=now();await db.batch([
    db.prepare("UPDATE document_templates SET status='retired',retired_by=?,retired_at=?,retirement_reason=? WHERE id=?").bind(input.actor,retiredAt,input.reason,id),
    auditStatement(db,{ aggregateType:'template',aggregateId:id,entityType:'document_template',entityId:id,action:'document_template_retired',actor:input.actor,createdAt:retiredAt,reason:input.reason,changes:[{ field:'status',oldValue:'active',newValue:'retired' }] }),
  ]);return listTemplateWorkspace(db);
}

async function versionById(db:D1Database,id:string):Promise<TemplateVersion|null> { const decisions=await decisionsByVersion(db);const row=await db.prepare('SELECT id,template_id AS templateId,version,title,description,types_json AS typesJson,exclude_flags_json AS excludeFlagsJson,section_order_json AS sectionOrderJson,required_in_package AS requiredInPackage,status,created_by AS createdBy,created_at AS createdAt,submitted_at AS submittedAt FROM document_template_versions WHERE id=?').bind(id).first<TemplateVersionRow>();return row ? templateVersionFromRow(row,decisions.get(id)) : null; }
async function baselineById(db:D1Database,id:string) { return db.prepare("SELECT id,label,status,approved_by AS approvedBy,approved_at AS approvedAt FROM baselines WHERE id=? AND status IN ('approved','superseded')").bind(id).first<{ id:string;label:string;status:string;approvedBy:string|null;approvedAt:string|null }>(); }
async function buildModel(db:D1Database,baselineId:string,version:TemplateVersion,code:string):Promise<RenderedDocumentModel> { const baseline=await baselineById(db,baselineId);if (!baseline) throw new WorkflowConflictError('Document outputs require an approved or historically approved baseline.');const evidence=await listEvidenceForBaseline(db,baseline.id);const selected=evidence.filter((item) => version.types.includes(item.type) && !item.flags.some((flag) => version.excludeFlags.includes(flag)));return { title:version.title,description:version.description,code,baseline:{ id:baseline.id,label:baseline.label,approvedBy:baseline.approvedBy,approvedAt:baseline.approvedAt },template:{ id:version.templateId,versionId:version.id,version:version.version },sections:version.sectionOrder.map((type) => ({ type,title:typeTitle(type),items:selected.filter((item) => item.type===type) })) }; }
async function storeFile(bucket:R2Bucket,args:{ ownerKind:'snapshot'|'redline'|'package';ownerId:string;format:'pdf'|'docx'|'zip';filename:string;bytes:Uint8Array;createdAt:string }) { const id=makeId('DFL');const sha256=await sha256Hex(bytesBuffer(args.bytes));const objectKey=`${args.ownerKind==='snapshot'?'document-snapshots':args.ownerKind==='redline'?'redlines':'document-packages'}/${args.ownerId}/${id}`;const contentType=args.format==='pdf'?'application/pdf':args.format==='docx'?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':'application/zip';await bucket.put(objectKey,args.bytes,{ httpMetadata:{ contentType },customMetadata:{ filename:args.filename,sha256 } });return { id,ownerKind:args.ownerKind,ownerId:args.ownerId,format:args.format,filename:args.filename,contentType,size:args.bytes.byteLength,sha256,objectKey,createdAt:args.createdAt }; }
function fileInsert(db:D1Database,file:Awaited<ReturnType<typeof storeFile>>) { return db.prepare('INSERT INTO document_files (id,owner_kind,owner_id,format,filename,content_type,size,sha256,object_key,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(file.id,file.ownerKind,file.ownerId,file.format,file.filename,file.contentType,file.size,file.sha256,file.objectKey,file.createdAt); }
async function filesFor(db:D1Database,ownerId:string) { const rows=await db.prepare('SELECT id,owner_kind AS ownerKind,owner_id AS ownerId,format,filename,content_type AS contentType,size,sha256,created_at AS createdAt FROM document_files WHERE owner_id=? ORDER BY format').bind(ownerId).all<Record<string,unknown>>();return rows.results.map((row) => DocumentFileSchema.parse(row)); }

export async function getDocumentSnapshot(db:D1Database,id:string):Promise<DocumentSnapshot|null> { await ensureWorkspace(db);const row=await db.prepare('SELECT id,document_id AS documentId,baseline_id AS baselineId,template_version_id AS templateVersionId,source_versions_json AS sourceVersionsJson,renderer_version AS rendererVersion,fingerprint,rendered_model_json AS renderedModelJson,rendered_at AS renderedAt FROM document_snapshots WHERE id=?').bind(id).first<{ id:string;documentId:string;baselineId:string;templateVersionId:string;sourceVersionsJson:string;rendererVersion:string;fingerprint:string;renderedModelJson:string;renderedAt:string }>();return row ? DocumentSnapshotSchema.parse({ ...row,sourceVersionIds:StringArraySchema.parse(parseJson(row.sourceVersionsJson)),model:parseJson(row.renderedModelJson),files:await filesFor(db,id) }) : null; }

export async function createDocumentSnapshot(db:D1Database,bucket:R2Bucket,raw:unknown):Promise<DocumentSnapshot> {
  await ensureWorkspace(db);const input=CreateDocumentSnapshotInputSchema.parse(raw);const version=await versionById(db,input.templateVersionId);if (!version) throw new InvalidRequestError('Template version not found.');if (version.status!=='approved') throw new WorkflowConflictError('Only approved template versions can create controlled snapshots.');const template=await db.prepare("SELECT code,status FROM document_templates WHERE id=?").bind(version.templateId).first<{ code:string;status:string }>();if (!template) throw new InvalidRequestError('Template not found.');const model=await buildModel(db,input.baselineId,version,template.code);const sourceVersionIds=model.sections.flatMap((section) => section.items.map((item) => item.versionId));const fingerprint=await hashJson({ baselineId:input.baselineId,templateVersionId:version.id,sourceVersionIds,rendererVersion:DOCUMENT_RENDERER_VERSION });const id=DocumentSnapshotSchema.shape.id.parse(`SNAP-${version.id}-${input.baselineId}`);const existing=await getDocumentSnapshot(db,id);if (existing) { if (existing.fingerprint!==fingerprint) throw new WorkflowConflictError('The existing snapshot fingerprint does not match the current controlled input.');return existing; }
  const renderedAt=now();const bytes=await renderSnapshot(model);const code=template.code.toLowerCase();const stored=[await storeFile(bucket,{ ownerKind:'snapshot',ownerId:id,format:'pdf',filename:`${code}-${model.baseline.label}.pdf`,bytes:bytes.pdf,createdAt:renderedAt }),await storeFile(bucket,{ ownerKind:'snapshot',ownerId:id,format:'docx',filename:`${code}-${model.baseline.label}.docx`,bytes:bytes.docx,createdAt:renderedAt })];
  try { await db.batch([
    db.prepare('INSERT INTO document_snapshots (id,document_id,baseline_id,template_version_id,source_versions_json,renderer_version,fingerprint,rendered_model_json,rendered_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,version.templateId,input.baselineId,version.id,JSON.stringify(sourceVersionIds),DOCUMENT_RENDERER_VERSION,fingerprint,JSON.stringify(model),renderedAt),...stored.map((file) => fileInsert(db,file)),
    auditStatement(db,{ aggregateType:'baseline',aggregateId:input.baselineId,entityType:'document_snapshot',entityId:id,action:'document_snapshot_created',actor:input.actor,createdAt:renderedAt,references:{ templateVersionId:version.id,fingerprint } }),
  ]); } catch (error:unknown) { await bucket.delete(stored.map((file) => file.objectKey));throw error; }const result=await getDocumentSnapshot(db,id);if (!result) throw new Error('Created snapshot could not be loaded.');return result;
}

export async function createDocumentRedline(db:D1Database,bucket:R2Bucket,raw:unknown) {
  await ensureWorkspace(db);const input=CreateDocumentRedlineInputSchema.parse(raw);const [before,after]=await Promise.all([getDocumentSnapshot(db,input.fromSnapshotId),getDocumentSnapshot(db,input.toSnapshotId)]);if (!before || !after) throw new InvalidRequestError('Both snapshots must exist.');if (before.documentId!==after.documentId) throw new InvalidRequestError('Controlled redlines require snapshots of the same template.');if (before.id===after.id) throw new InvalidRequestError('Choose two different snapshots.');const diff=diffDocumentModels(before.model,after.model);const fingerprint=await hashJson({ from:before.id,to:after.id,version:DOCUMENT_REDLINE_VERSION,diff });const id=`DRL-${fingerprint.slice(0,16).toUpperCase()}`;const existing=await getDocumentRedline(db,id);if (existing) return existing;const createdAt=now();const report={ title:`${after.model.code} controlled document redline`,subtitle:`${before.model.baseline.label} to ${after.model.baseline.label}`,templateChanges:diff.templateChanges,changes:diff.contentChanges.map((change) => ({ kind:change.kind,label:change.itemId,before:change.before,after:change.after })) };const rendered=await renderRedline(report);const stored=[await storeFile(bucket,{ ownerKind:'redline',ownerId:id,format:'pdf',filename:`${after.model.code.toLowerCase()}-redline.pdf`,bytes:rendered.pdf,createdAt}),await storeFile(bucket,{ ownerKind:'redline',ownerId:id,format:'docx',filename:`${after.model.code.toLowerCase()}-redline.docx`,bytes:rendered.docx,createdAt})];
  try { await db.batch([db.prepare('INSERT INTO document_redlines (id,template_id,from_snapshot_id,to_snapshot_id,algorithm_version,fingerprint,changes_json,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,before.documentId,before.id,after.id,DOCUMENT_REDLINE_VERSION,fingerprint,JSON.stringify(diff),input.actor,createdAt),...stored.map((file) => fileInsert(db,file)),auditStatement(db,{ aggregateType:'template',aggregateId:before.documentId,entityType:'document_redline',entityId:id,action:'document_redline_created',actor:input.actor,createdAt,references:{ fromSnapshotId:before.id,toSnapshotId:after.id,fingerprint } })]); } catch (error:unknown) { await bucket.delete(stored.map((file) => file.objectKey));throw error; }return getDocumentRedline(db,id);
}

export async function getDocumentRedline(db:D1Database,id:string) { await ensureWorkspace(db);const row=await db.prepare('SELECT id,template_id AS templateId,from_snapshot_id AS fromSnapshotId,to_snapshot_id AS toSnapshotId,algorithm_version AS algorithmVersion,fingerprint,changes_json AS changesJson,created_by AS createdBy,created_at AS createdAt FROM document_redlines WHERE id=?').bind(id).first<{ id:string;templateId:string;fromSnapshotId:string;toSnapshotId:string;algorithmVersion:string;fingerprint:string;changesJson:string;createdBy:string;createdAt:string }>();if (!row) return null;const changes=z.object({ templateChanges:z.array(z.string()),contentChanges:z.array(z.unknown()) }).parse(parseJson(row.changesJson));return DocumentRedlineSchema.parse({ ...row,...changes,files:await filesFor(db,id) }); }

async function currentPackageFingerprint(db:D1Database,baselineId:string) { const rows=await db.prepare("SELECT t.id AS templateId,t.current_version_id AS templateVersionId FROM document_templates t JOIN document_template_versions v ON v.id=t.current_version_id WHERE t.status='active' AND v.status='approved' AND v.required_in_package=1 ORDER BY t.code").all<{ templateId:string;templateVersionId:string }>();return { fingerprint:await hashJson({ baselineId,rendererVersion:DOCUMENT_RENDERER_VERSION,policy:DOCUMENT_PACKAGE_POLICY,templates:rows.results }),templates:rows.results }; }
async function objectVerified(bucket:R2Bucket,file:{ objectKey:string;sha256:string;size:number }) { const head=await bucket.head(file.objectKey);return Boolean(head && head.size===file.size && head.customMetadata?.sha256===file.sha256); }

export async function createDocumentPackage(db:D1Database,bucket:R2Bucket,raw:unknown) {
  await ensureWorkspace(db);const input=CreateDocumentPackageInputSchema.parse(raw);const baseline=await baselineById(db,input.baselineId);const current=await currentPackageFingerprint(db,input.baselineId);const id=DocumentPackageSchema.options[0].shape.id.parse(`DPK-${current.fingerprint.slice(0,16).toUpperCase()}`);const existing=await getDocumentPackage(db,id);if (existing) return existing;const createdAt=now();const results:Array<{ id:string;code:string;status:'pass'|'block';subjectId:string;title:string;detail:string }>=[];const entries:Array<{ templateId:string;templateVersionId:z.infer<typeof TemplateVersionIdSchema>;snapshotId:z.infer<typeof DocumentSnapshotSchema.shape.id> }>=[];
  if (!baseline) results.push({ id:'DPK-BASELINE',code:'DPK-001',status:'block',subjectId:input.baselineId,title:'Approved baseline required',detail:'The selected baseline is not approved or historically approved.' });
  for (const reference of current.templates) { try { const snapshot=await createDocumentSnapshot(db,bucket,{ baselineId:input.baselineId,templateVersionId:reference.templateVersionId,actor:input.actor });entries.push({ templateId:reference.templateId,templateVersionId:snapshot.templateVersionId,snapshotId:snapshot.id });const formats=new Set(snapshot.files.map((file) => file.format));for (const format of ['pdf','docx'] as const) if (!formats.has(format)) results.push({ id:`DPK-${reference.templateId}-${format}`,code:'DPK-003',status:'block',subjectId:reference.templateId,title:`Missing ${format.toUpperCase()} output`,detail:`${snapshot.id} has no ${format.toUpperCase()} file.` });const storedRows=await db.prepare('SELECT object_key AS objectKey,sha256,size,format FROM document_files WHERE owner_id=?').bind(snapshot.id).all<{ objectKey:string;sha256:string;size:number;format:string }>();for (const file of storedRows.results) if (!await objectVerified(bucket,file)) results.push({ id:`DPK-${reference.templateId}-${file.format}-OBJECT`,code:'DPK-006',status:'block',subjectId:reference.templateId,title:'Stored object mismatch',detail:`The ${file.format.toUpperCase()} object is missing or its stored metadata does not match D1.` }); } catch (error:unknown) { results.push({ id:`DPK-${reference.templateId}-SNAPSHOT`,code:'DPK-002',status:'block',subjectId:reference.templateId,title:'Required snapshot unavailable',detail:error instanceof Error?error.message:'Snapshot generation failed.' }); } }
  if (current.templates.length===0) results.push({ id:'DPK-TEMPLATES',code:'DPK-002',status:'block',subjectId:input.baselineId,title:'No required templates',detail:'No active approved template is marked as required.' });if (results.length===0) results.push({ id:'DPK-COMPLETE',code:'DPK-000',status:'pass',subjectId:input.baselineId,title:'Required outputs complete',detail:`${entries.length} required templates have PDF and DOCX outputs whose R2 metadata matches D1.` });
  let manifest:Record<string,unknown>|null=null;let zipFile:Awaited<ReturnType<typeof storeFile>>|null=null;
  if (!results.some((result) => result.status==='block')) { const files:Record<string,Uint8Array>={};const manifestEntries=[];for (const entry of entries) { const snapshot=await getDocumentSnapshot(db,entry.snapshotId);if (!snapshot) throw new Error('Package snapshot disappeared.');const stored=await db.prepare('SELECT filename,format,size,sha256,object_key AS objectKey FROM document_files WHERE owner_id=? ORDER BY format').bind(snapshot.id).all<{ filename:string;format:string;size:number;sha256:string;objectKey:string }>();for (const file of stored.results) { const object=await bucket.get(file.objectKey);if (!object) throw new WorkflowConflictError(`Stored output ${file.filename} is missing.`);files[file.filename]=new Uint8Array(await object.arrayBuffer()); }manifestEntries.push({ templateId:entry.templateId,templateVersionId:entry.templateVersionId,snapshotId:entry.snapshotId,sourceVersionIds:snapshot.sourceVersionIds,files:stored.results.map(({ objectKey:_objectKey,...file }) => file) }); }manifest={ schema:'document-package-v1',packageId:id,baseline:{ id:baseline?.id,label:baseline?.label,status:baseline?.status,approvedBy:baseline?.approvedBy,approvedAt:baseline?.approvedAt },policy:DOCUMENT_PACKAGE_POLICY,rendererVersion:DOCUMENT_RENDERER_VERSION,inputFingerprint:current.fingerprint,createdAt,entries:manifestEntries };files['manifest.json']=new TextEncoder().encode(JSON.stringify(manifest,null,2));zipFile=await storeFile(bucket,{ ownerKind:'package',ownerId:id,format:'zip',filename:`bluebridge-${baseline?.label??input.baselineId}-document-package.zip`,bytes:buildZip(files),createdAt }); }
  const status=zipFile?'ready_for_qa':'blocked';const statements:D1PreparedStatement[]=[db.prepare('INSERT INTO document_packages (id,baseline_id,policy_id,policy_version,renderer_version,input_fingerprint,status,manifest_json,zip_file_id,created_by,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(id,input.baselineId,DOCUMENT_PACKAGE_POLICY.id,DOCUMENT_PACKAGE_POLICY.version,DOCUMENT_RENDERER_VERSION,current.fingerprint,status,manifest?JSON.stringify(manifest):null,zipFile?.id??null,input.actor,createdAt),...entries.map((entry) => db.prepare('INSERT INTO document_package_entries (package_id,template_id,template_version_id,snapshot_id) VALUES (?,?,?,?)').bind(id,entry.templateId,entry.templateVersionId,entry.snapshotId)),...results.map((result) => db.prepare('INSERT INTO document_package_results (package_id,result_id,code,status,subject_id,title,detail) VALUES (?,?,?,?,?,?,?)').bind(id,result.id,result.code,result.status,result.subjectId,result.title,result.detail)),auditStatement(db,{ aggregateType:'baseline',aggregateId:input.baselineId,entityType:'document_package',entityId:id,action:'document_package_evaluated',actor:input.actor,createdAt,changes:[{ field:'status',oldValue:null,newValue:status }],references:{ inputFingerprint:current.fingerprint,policyId:DOCUMENT_PACKAGE_POLICY.id } })];if (zipFile) statements.push(fileInsert(db,zipFile));try { await db.batch(statements); } catch (error:unknown) { if (zipFile) await bucket.delete(zipFile.objectKey);throw error; }return getDocumentPackage(db,id);
}

export async function getDocumentPackage(db:D1Database,id:string) { await ensureWorkspace(db);const row=await db.prepare('SELECT id,baseline_id AS baselineId,policy_id AS policyId,policy_version AS policyVersion,renderer_version AS rendererVersion,input_fingerprint AS inputFingerprint,status,manifest_json AS manifestJson,zip_file_id AS zipFileId,created_by AS createdBy,created_at AS createdAt FROM document_packages WHERE id=?').bind(id).first<{ id:string;baselineId:string;policyId:string;policyVersion:string;rendererVersion:string;inputFingerprint:string;status:string;manifestJson:string|null;zipFileId:string|null;createdBy:string;createdAt:string }>();if (!row) return null;const entries=await db.prepare('SELECT template_id AS templateId,template_version_id AS templateVersionId,snapshot_id AS snapshotId FROM document_package_entries WHERE package_id=? ORDER BY template_id').bind(id).all<Record<string,unknown>>();const results=await db.prepare('SELECT result_id AS id,code,status,subject_id AS subjectId,title,detail FROM document_package_results WHERE package_id=? ORDER BY code,result_id').bind(id).all<Record<string,unknown>>();const decision=await db.prepare('SELECT decision,reason,actor,created_at AS createdAt FROM document_package_decisions WHERE package_id=? ORDER BY created_at DESC,id DESC LIMIT 1').bind(id).first<{ decision:'accepted'|'rejected';reason:string;actor:string;createdAt:string }>();const zipFile=row.zipFileId?(await filesFor(db,id)).find((file) => file.id===row.zipFileId)??null:null;const status=decision?.decision==='accepted'?'accepted':decision?.decision==='rejected'?'rejected':row.status;return DocumentPackageSchema.parse({ ...row,status,manifest:row.manifestJson?parseJson(row.manifestJson):null,zipFile,decision:decision??null,entries:entries.results,results:results.results }); }

export async function decideDocumentPackage(db:D1Database,id:string,raw:unknown) {
  await ensureWorkspace(db);const input=DecideDocumentPackageInputSchema.parse(raw);const currentPackage=await getDocumentPackage(db,id);if(!currentPackage)return null;
  const current=await currentPackageFingerprint(db,currentPackage.baselineId);const latest=await db.prepare("SELECT input_fingerprint AS fingerprint FROM document_packages WHERE baseline_id=? AND status='ready_for_qa' ORDER BY created_at DESC,id DESC LIMIT 1").bind(currentPackage.baselineId).first<{ fingerprint:string }>();
  if(!canAcceptDocumentPackage({packageFingerprint:currentPackage.inputFingerprint,currentFingerprint:current.fingerprint,latestPassingFingerprint:latest?.fingerprint??null,status:currentPackage.status}))throw new WorkflowConflictError('QA may decide only the latest passing package fingerprint. Rebuild the controlled package after any input change.');
  const createdAt=now();await db.batch([db.prepare('INSERT INTO document_package_decisions (id,package_id,input_fingerprint,decision,reason,actor,created_at) VALUES (?,?,?,?,?,?,?)').bind(makeId('DPD'),id,currentPackage.inputFingerprint,input.decision,input.reason,input.actor,createdAt),db.prepare('UPDATE document_packages SET status=? WHERE id=?').bind(input.decision==='accepted'?'accepted':'rejected',id),auditStatement(db,{ aggregateType:'baseline',aggregateId:currentPackage.baselineId,entityType:'document_package',entityId:id,action:`document_package_${input.decision}`,actor:input.actor,createdAt,reason:input.reason,changes:[{ field:'status',oldValue:'ready_for_qa',newValue:input.decision==='accepted'?'accepted':'rejected' }],references:{ inputFingerprint:currentPackage.inputFingerprint } })]);return getDocumentPackage(db,id);
}

export async function downloadDocumentFile(db:D1Database,bucket:R2Bucket,id:string) { await ensureWorkspace(db);const file=await db.prepare('SELECT owner_kind AS ownerKind,owner_id AS ownerId,filename,content_type AS contentType,sha256,object_key AS objectKey FROM document_files WHERE id=?').bind(id).first<{ ownerKind:string;ownerId:string;filename:string;contentType:string;sha256:string;objectKey:string }>();if (!file) return null;if (file.ownerKind==='package') { const pkg=await db.prepare("SELECT status FROM document_packages WHERE id=?").bind(file.ownerId).first<{ status:string }>();if (pkg?.status!=='accepted') throw new WorkflowConflictError('The controlled package is available only after QA acceptance.'); }const object=await bucket.get(file.objectKey);if (!object) return null;return new Response(object.body,{ headers:{ 'content-type':file.contentType,'content-disposition':`attachment; filename="${normalizeFilename(file.filename).replaceAll('"','_')}"`,'etag':file.sha256,'x-content-type-options':'nosniff' } }); }
export async function documentObjectKeys(db:D1Database):Promise<string[]> { await ensureWorkspace(db);const rows=await db.prepare('SELECT object_key AS objectKey FROM document_files').all<{ objectKey:string }>();return rows.results.map((row) => row.objectKey); }
