'use client';

import { useEffect, useMemo, useState } from 'react';
import { TraceabilityCoverageSchema, type CoverageCell, type TraceabilityCoverageView } from '@/lib/traceability';

function Cell({ cell }:{ cell:CoverageCell }) {
  if (cell.status === 'gap') return <span className="coverage-gap">Gap</span>;
  return <span className="coverage-links">{cell.links.map((link) => <a key={link.relationshipId} href={`/?evidence=${link.itemId}`} title={link.relationshipId}>{link.itemId}</a>)}</span>;
}

export default function TraceabilityPage() {
  const [coverage,setCoverage] = useState<TraceabilityCoverageView|null>(null);
  const [error,setError] = useState<string|null>(null);
  const [gapsOnly,setGapsOnly] = useState(false);
  useEffect(() => { void fetch('/api/traceability').then(async (response) => { if (!response.ok) throw new Error('Could not load traceability coverage.'); return TraceabilityCoverageSchema.parse(await response.json()); }).then(setCoverage).catch((reason:unknown) => setError(reason instanceof Error ? reason.message : 'Could not load traceability coverage.')); },[]);
  const requirements = useMemo(() => coverage?.requirements.filter((row) => !gapsOnly || [row.userNeed,row.design,row.verification].some((cell) => cell.status === 'gap')) ?? [],[coverage,gapsOnly]);
  const controls = useMemo(() => coverage?.riskControls.filter((row) => !gapsOnly || [row.hazard,row.verification].some((cell) => cell.status === 'gap')) ?? [],[coverage,gapsOnly]);
  if (error) return <main className="trace-shell"><div className="error-banner">{error}</div></main>;
  if (!coverage) return <main className="trace-shell"><p>Calculating baseline coverage…</p></main>;
  return <main className="trace-shell">
    <header className="trace-header"><div><p className="eyebrow teal">RhythmReview · {coverage.baseline.label}</p><h1>Traceability coverage</h1><p className="lede">Deterministic coverage from stored typed relationships in the active approved baseline. A gap means the expected direct link is absent; it is not an AI judgment.</p></div><a className="secondary-button" href="/">← Evidence workspace</a></header>
    <section className="trace-summary"><article><span>Coverage checks</span><strong>{coverage.summary.totalChecks}</strong></article><article><span>Covered</span><strong>{coverage.summary.coveredChecks}</strong></article><article className={coverage.summary.gaps ? 'alert' : ''}><span>Missing links</span><strong>{coverage.summary.gaps}</strong></article><article className={coverage.summary.highCriticalityGaps ? 'alert' : ''}><span>High-criticality items with gaps</span><strong>{coverage.summary.highCriticalityGaps}</strong></article></section>
    <div className="trace-toolbar"><label><input type="checkbox" checked={gapsOnly} onChange={(event) => setGapsOnly(event.target.checked)} /> Show gaps only</label><span>Relationship directions follow the stored graph, not inferred dependency semantics.</span></div>
    <section className="trace-section"><div className="section-heading"><div><p className="eyebrow">Design controls</p><h2>Requirement coverage</h2></div><span>{requirements.length} requirements</span></div><div className="trace-table-wrap"><table className="trace-table"><thead><tr><th>Requirement</th><th>User need</th><th>Design</th><th>Verification</th></tr></thead><tbody>{requirements.map((row) => <tr key={row.id}><th><a href={`/?evidence=${row.id}`}>{row.id}</a><b>{row.title}</b><small>{row.criticality}</small></th><td><Cell cell={row.userNeed} /></td><td><Cell cell={row.design} /></td><td><Cell cell={row.verification} /></td></tr>)}</tbody></table></div></section>
    <section className="trace-section"><div className="section-heading"><div><p className="eyebrow">Risk management</p><h2>Risk-control coverage</h2></div><span>{controls.length} controls</span></div><div className="trace-table-wrap"><table className="trace-table"><thead><tr><th>Risk control</th><th>Hazard</th><th>Verification</th></tr></thead><tbody>{controls.map((row) => <tr key={row.id}><th><a href={`/?evidence=${row.id}`}>{row.id}</a><b>{row.title}</b><small>{row.criticality}</small></th><td><Cell cell={row.hazard} /></td><td><Cell cell={row.verification} /></td></tr>)}</tbody></table></div></section>
    <style jsx global>{`
      .trace-shell{max-width:1440px;margin:0 auto;padding:40px 48px 80px}.trace-header{display:flex;justify-content:space-between;gap:32px;align-items:flex-start}.trace-header h1{font-size:42px;margin:6px 0 10px}.trace-summary{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:30px 0}.trace-summary article{border:1px solid #d9dedc;border-radius:12px;padding:18px;background:#fff}.trace-summary span{display:block;font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:#64706b}.trace-summary strong{display:block;font-size:32px;margin-top:8px}.trace-summary .alert{border-color:#d7a48c;background:#fff8f4}.trace-toolbar{display:flex;justify-content:space-between;gap:20px;padding:14px 16px;background:#f4f6f5;border-radius:10px;margin-bottom:28px;font-size:13px}.trace-section{margin-top:34px}.trace-table-wrap{overflow:auto;border:1px solid #d9dedc;border-radius:12px}.trace-table{width:100%;border-collapse:collapse;background:#fff}.trace-table th,.trace-table td{padding:14px 16px;border-bottom:1px solid #e7eae8;text-align:left;vertical-align:top}.trace-table thead th{font-size:12px;text-transform:uppercase;letter-spacing:.05em;background:#f7f8f7}.trace-table tbody th{min-width:280px}.trace-table tbody th>a{font-family:monospace;margin-right:10px}.trace-table tbody th b{display:block;margin-top:6px}.trace-table tbody th small{display:block;margin-top:5px;color:#6d7773;text-transform:capitalize}.coverage-links{display:flex;flex-wrap:wrap;gap:6px}.coverage-links a{font-family:monospace;font-size:12px;padding:5px 7px;border-radius:6px;background:#edf5f1;color:#175c46;text-decoration:none}.coverage-gap{display:inline-block;padding:5px 8px;border-radius:6px;background:#fff0e8;color:#9a431e;font-weight:700;font-size:12px}.secondary-button{text-decoration:none}@media(max-width:800px){.trace-shell{padding:24px 18px}.trace-header{display:block}.trace-header .secondary-button{display:inline-block;margin-top:18px}.trace-summary{grid-template-columns:1fr 1fr}.trace-toolbar{display:block}.trace-toolbar span{display:block;margin-top:8px}}
    `}</style>
  </main>;
}
